### ISSUE TITLE
A mistake

### ISSUE THREAD

**Issue by lazyFrogLOL** [oreillymedia/iOS7_Programming_Cookbook#3]
I have found a mistake in chapter 2,recipe 2.4.The code describe a method initWithItem:point:attachedToAnchor,but this instance method is not existed.

**Comment by karent** [comment]
Thank you for your feedback. I've posted this on the book's errata page so that it can be addressed by the author. You can see the reported errata here: http://www.oreilly.com/catalog/errataunconfirmed.csp?isbn=0636920031031
